# ANOVA Test

Analysis of Variance (ANOVA) is a statistical method used to compare the means of two or more groups to determine if there are any significant differences among them. ANOVA is particularly useful when dealing with multiple groups, as it allows for simultaneous comparisons.

It is a generalization of the [t-test](https://en.wikipedia.org/wiki/Student%27s_t-test) when the number of groups to compare is more than two.

One could in principle perform a series of t-tests on pairs of groups. However the final results would be hard to interpret and understand.

ANOVA will instead return one number (called the  `F-statistic`) and one `p-value` to interpret it.

## Types of ANOVA tests
There are three types of ANOVA tests:
- One-way ANOVA
- Two-way ANOVA
- ANOVA with repeated measures

While this lecture will focus mostly on the one-way ANOVA, let us understand the differences among the three types of analysis of variance and when they are used.

### One-way ANOVA

The **one-way ANOVA** is used to perform tests of hypothesis. It tests whether there are statistically significant differences among the mean values of three or more groups. 

As an example, let us imagine that a coffee company wants to start selling coffee online, but is unsure of the website design. Should it use this or that image? Should this phrase be more catchy? The shareholders select than twenty-four of their top buying customers and randomly divide them in three groups of eight members. Each group will  test a slightly different version of the website. For each customer, the website will record the amount of coffee sold in Euro. The goal of the experiment is to find the version of the website that maximizes the sales of coffee. The versions of the website are _coffee website v1_, _coffee website v2_ and _coffee website v3_.

![one_way.png](./images/one_way.png)

For the hypothesis test to be valid, the groups must fulfill the following assumptions:
- **Level of measurement**: the independent variable must be a *categorical* variable. This variable in fact is used to identify the groups. In our example, it is the version of the website (e.g. _coffee website v3_). The dependent variable instead has to be a *numerical* variable. In other words, something that is measured. In our example, the amount of coffee sold, measured in Euro.
- **Independence**: the measured values of one group must **not** be influenced or influence the measures of another group.
- **Normality**: measured values must follow a [Normal](https://en.wikipedia.org/wiki/Normal_distribution) distribution.
- **Homogeneity of variance**: the variance in each group should be roughly the same.

The null hypothesis for the one-way ANOVA reads:

> The mean of the coffee sales are the same across the three groups.

The alternative hypothesis instead reads:

> The mean of the coffee sales are different across the three groups.

### Two-way ANOVA
The **two-way ANOVA** is used to perform tests of hypothesis. In this case, however, it tests how two categorical (independent) variables affect a numerical (dependent) variable.

Going back to our coffee website experiment, let us assume that the shareholders of the company would also like to see how the sales of coffee are influenced by the age of their top buying customers. They decide to extend the experiment to forty-eight people. They divide them based on their age (*age group 1* for customers with an age below  fifty years and *age group 2* for customers older than fifty years). Each age group is then randomly divided into three sub-groups. Each sub-group will be assigned to a website version. The questions that the company shareholders seek to answer with this experiment are:
- Does the website version have an effect on the coffee sold?
- Does the age of the customers have an effect on the coffee sold?
- Is there any interaction effect between the age of the customers and the website version?

![two_way.png](./images/two_way.png)

For the hypothesis test to be valid, the groups must fulfill the same assumptions of the **one-way ANOVA**.

There are three null hypothesis and therefore also three alternative hypothesis. The null hypothesis are:
> **First null hypothesis**: the website version does not change the mean of the coffee sales.

> **Second null hypothesis**: age does not change the mean of the coffee sales.

> **Third null hypothesis**: the website version does not influence the way age affects the coffee sales.

The alternative hypothesis are:
> **First alternative hypothesis**: the website version changes the mean of the coffee sales.

> **Second alternative hypothesis**: age changes the mean of the coffee sales.

> **Third alternative hypothesis**: the website version modifies the way age affects the coffee sales.


### ANOVA with repeated measures

This type of analysis of variance is used when the same subjects are measured several times under different conditions.

Going back to our coffee website experiment, let us assume that the experiments were successful and that *coffee website v1* was found to be the version of the website with the highest coffee sales. The shareholders are now interested in monitoring how the coffee sales vary during the year. They therefore select eight top buying customers and record their coffee purchases on *March 31st*, *June 30th*, *September 30th* and *December 31st*.

![repeated.png](./images/repeated.png)

The null hypothesis is that there are **no** differences among the four dates. The alternative hypothesis is that there are indeed differences.

## How the one-way ANOVA works

Let us now focus on the one-way ANOVA and how to compute the `F-statistic` and the `p-value` to interpret it.

Following the example proposed before for the one-way ANOVA, let us consider the twenty-four input data points available under the sub-directory `data/` in the csv file `coffee_website.csv`.

The `F-statistic` is given by the ratio of the *Variance among groups* over the *Variance within each group*. The variance among the groups measures the spread among the mean values of the groups. The variance within each group is the usual definition of variance. A large `F-statistic` means that the variance among groups is high (hence the differences among the groups might very well be statistically significant). A low `F-statistic` means the opposite. But how can we tell if an F-statistic is high or low? To get a definitive answer we need the `p-value`.

### How the `F-statistic` is computed

The total number of users is identified by $N_\text{users}=24$. Each group is composed of `n=8` top buying customers. Therefore the number of groups is $N_\text{groups}=3$.

To compute the `F-statistic` we need first the mean of all the data $\mu$ across the groups and the mean values within each group $\mu_i$ (where $i$ is the index that identifies the group). We have that:
$$
\mu = \frac{\sum^{N_\text{users}}_{k=1} x_k}{N_\text{users}}=\frac{128}{24}=5.333.
$$

The mean values within each group is instead given by $\mu_i = \frac{\sum^n_{m=1} x_m}{n}$. They are equal to:
- **coffee website v1**: $\mu_1$ = 20/8 =  2.5
- **coffee website v2**: $\mu_2$ = 64/8 = 8
- **coffee website v3**: $\mu_3$ = 44/8 = 5.5

We can now compute the **Sum of Squares between the groups**
$$
SS_{btg} = \sum^{N_\text{groups}}_{i=1} n \left( \mu_i - \mu \right)^2
$$
Let us now calculate the **Sum of Squares within the groups**
$$
SS_{wtg} = \sum^{N_\text{groups}}_{i=1} \sum^n_{m=1} \left( x_{m,i} - \mu_i \right)^2
$$

The variances among the groups (also commonly referred to as *mean squares*) is given by
$$
 MS_{btg} = \frac{SS_{btg}}{df_{btg}}
$$
where $df_{btg}$ is the number of degrees of freedom among the groups and it is given by $df_{btg}=N_\text{groups}-1$ (in our example $df_{btg}=2$). Moreover
$$
MS_{wtg} = \frac{SS_{wtg}}{df_{wtg}},
$$
where $df_{wtg}=N_\text{users}-N_\text{groups}$ (in our example $df_{wtg}=24-3=21$). The `F-statistic` is then
$$
\text{F-statistic} = \frac{MS_{btg}}{MS_{wtg}}.
$$

## How to implement the one-way ANOVA in Python

The sub-directory `data/` contains a csv file (`coffee_website.csv`) with 24 data points. Let us load them into a pandas dataframe and compute the `F-statistic` and `p-value`.

In [1]:
import pandas as pd
# Scipy implements ANOVA
import scipy.stats as stats

# Read the input data to a pandas DataFrame
input_df = pd.read_csv('data/coffee_website.csv')

In [2]:
input_df

    Unnamed: 0  value              group
0            0    3.0  coffee website v1
1            1    2.0  coffee website v1
2            2    1.0  coffee website v1
3            3    1.0  coffee website v1
4            4    4.0  coffee website v1
5            5    2.0  coffee website v1
6            6    4.0  coffee website v1
7            7    3.0  coffee website v1
8            8   10.0  coffee website v2
9            9    9.0  coffee website v2
10          10    9.0  coffee website v2
11          11    8.0  coffee website v2
12          12    7.0  coffee website v2
13          13    8.0  coffee website v2
14          14    6.0  coffee website v2
15          15    7.0  coffee website v2
16          16    7.0  coffee website v3
17          17    6.0  coffee website v3
18          18    7.0  coffee website v3
19          19    6.0  coffee website v3
20          20    5.0  coffee website v3
21          21    4.0  coffee website v3
22          22    3.0  coffee website v3
23          23    6.0  coffee website v3

In [3]:

# Create numpy arrays
website_v1_group = input_df[input_df["group"]=="coffee website v1"]["value"].to_numpy()
website_v2_group = input_df[input_df["group"]=="coffee website v2"]["value"].to_numpy()
website_v3_group = input_df[input_df["group"]=="coffee website v3"]["value"].to_numpy()

In [4]:
website_v1_group

array([3., 2., 1., 1., 4., 2., 4., 3.])

In [5]:
# Perform ANOVA test
f = stats.f_oneway(website_v1_group, website_v2_group, website_v3_group)

# Print the results
print(f'F-statistic: {f.statistic}')
print(f'P-value [%]: {f.pvalue*100:.10f}')

F-statistic: 35.38888888888889
P-value [%]: 0.0000188173

Being the `p-value` below 5 \%, the null hypothesis is rejected. Therefore, the mean of the coffee sales are different across the three groups.

In [6]:
input_df

    Unnamed: 0  value              group
0            0    3.0  coffee website v1
1            1    2.0  coffee website v1
2            2    1.0  coffee website v1
3            3    1.0  coffee website v1
4            4    4.0  coffee website v1
5            5    2.0  coffee website v1
6            6    4.0  coffee website v1
7            7    3.0  coffee website v1
8            8   10.0  coffee website v2
9            9    9.0  coffee website v2
10          10    9.0  coffee website v2
11          11    8.0  coffee website v2
12          12    7.0  coffee website v2
13          13    8.0  coffee website v2
14          14    6.0  coffee website v2
15          15    7.0  coffee website v2
16          16    7.0  coffee website v3
17          17    6.0  coffee website v3
18          18    7.0  coffee website v3
19          19    6.0  coffee website v3
20          20    5.0  coffee website v3
21          21    4.0  coffee website v3
22          22    3.0  coffee website v3
23          23    6.0  coffee website v3

In [7]:
# As an additional exercise to better cement how the ANOVA works,
# Let's try now to calculate the F-statistic on our own
mu = input_df['value'].mean()
print(f'Sample mean (μ): {mu}')

Sample mean (μ): 5.333333333333333

In [8]:
# Print group means
v1_mean = website_v1_group.mean()
v2_mean = website_v2_group.mean()
v3_mean = website_v3_group.mean()
print(f'V1 group mean: {v1_mean}')
print(f'V2 group mean: {v2_mean}')
print(f'V3 group mean: {v3_mean}')

V1 group mean: 2.5
V2 group mean: 8.0
V3 group mean: 5.5

In [9]:
# Calcualate between groups sum of squares
SSbtg = 0
SSbtg += 8 * pow(website_v1_group.mean() - mu, 2)
SSbtg += 8 * pow(website_v2_group.mean() - mu, 2)
SSbtg += 8 * pow(website_v3_group.mean() - mu, 2)

In [10]:
SSbtg

121.33333333333334

In [11]:
# Calculate within groups sum of squares
SSwtg = 0
SSwtg1 = 0
SSwtg2 = 0
SSwtg3 = 0
for value in website_v1_group:
  SSwtg1 += pow(value - v1_mean, 2)
for value in website_v2_group:
  SSwtg2 += pow(value - v2_mean, 2)
for value in website_v3_group:
  SSwtg3 += pow(value - v3_mean, 2)
SSwtg = SSwtg1 + SSwtg2 + SSwtg3

In [12]:
print(f'SSbtg: {SSbtg}')
print(f'SSwtg: {SSwtg}')

SSbtg: 121.33333333333334
SSwtg: 36.0

In [13]:
# Calculate between and within groups degrees of freedom
btg_dof = 3 - 1  # E.g: number of groups - 1 (in this case)
wtg_dof = 24 - 3  # E.g: total samples - number of groups

In [14]:
# Calculate between and within groups mean squares
MSbtg = SSbtg / btg_dof
MSwtg = SSwtg / wtg_dof

In [15]:
# Calculate the F-statistic as the ratio between the mean squares
F_stat = MSbtg / MSwtg

print(f'F-Statistic (manually calculated): {F_stat}')

F-Statistic (manually calculated): 35.38888888888889

As you can see, the two scores match (ignoring extremely small approximation errors).

But what about calculating the `p-value` manually?

It's not as easy, and it would require a bit of more advanced math.  The "old school" way to do it is by checking the [distribution table](https://www.saskoer.ca/app/uploads/sites/313/2020/05/F-Distribution-Table.pdf)

<img src="./images/table.png" alt="f-distribution table" width="600"/>

As we can see, selecting table for `alpha` = 0.05 (5%) and with 2|21 degrees of freedom, the F-statistic is **3.47**. This means that, in our sample, if we had a F-statistic of < 3.47, we would have had a > 5% chance that the variance difference could be random (not related by the different website versions), and might accept the null hypothesis. Since our score was much higher, we can already tell that the null hypothesis is rejected.

Want to verify it yourself? Try altering the underlying coffee website data until the F-score approximates 3.47 and see how the p-value calculated by scipy changes!