# Web Scraping

### What is it?

Web scraping is the art and practice of **retrieving information from a website**. Web scraping can be done manually and, in a sense, it's what we do every time we look up some information on the website or when we copy a table from a Wikipedia page and paste it into a spreadsheet.

That said, the most efficient way to scrape a website is through some kind of an automated script and we will explore this practice in Python using a well known scraping library called `BeautifulSoup`.

### How does it work?

1. The first step is to locate a website from which you want to extract some information that is embedded in it. It could be an e-Commerce, a news outlet, a weather site or any other website really.
2. You should then proceed to inspect and analyze the HTML source code of that web page to find the specific ids and tags that identify the information you're after.
3. The central part of a Python scraper is, of course, the script itself. You write an algorithm to instruct your program to use those tags and ids to retrieve the information you're after.
4. Finally, you manipulate your results into a data structure of your choice (csv, json, ...) that will allow you to interact with and use your scraped data.

<img src="images/web-scraping.png" width="600">

### Is it legal?

In general terms, web scraping is not illegal. More specifically, according to Wikipedia: *the legality of web scraping varies across the world. In general, web scraping may be against the terms of use of some websites, but the enforceability of these terms is unclear.*

It is generally accepted that, if a website makes its data public, then scraping it should be legal. This is reinforced by legal cases such as "LinkedIn vs hiQ Labs". You can read more on [Wikipedia](https://en.wikipedia.org/wiki/Web_scraping#Legal_issues) and [online](https://www.parsehub.com/blog/web-scraping-legal/).

### A first simple example

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

We will start with a [simple page](https://www.scrapethissite.com/pages/simple/), click on the link and familiarise yourself with its contents; it contains a list of country names from the world and some information for each one of them.

Before moving on, inspect the underlying HTML code: right click on an element of the page (for example the name "Andorra") and select "Inspect". This will open the Inspect Element window in your Chrome browser, which allows you to see the code that generates the page you're looking at.

<img src="images/inspect-element.png" width="600">

In Python, let's start by sending an HTTP GET request to retrieve the HTML content of a desired web page and print to screen the first 1000 characters:

In [2]:
url = "https://www.scrapethissite.com/pages/simple/"
page = requests.get(url)

print(page.text[0:1000])

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Countries of the World: A Simple Example | Scrape This Site | A public sandbox for learning web scraping</title>
    <link rel="icon" type="image/png" href="/static/images/scraper-icon.png" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A single page that lists information about all the countries in the world. Good for those just get started with web scraping.">

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Lato:400,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/css/styles.css">


<meta name=

In [3]:
type(page.text)

str

Then we create a Beautiful Soup object named `soup` that takes `page.content` as an input (this is the HTML content we just printed to screen).

*Note: it is better to pass page.content instead of page.text to avoid issues with character encoding.*

In [4]:
soup = BeautifulSoup(page.content, "html.parser")

In [5]:
type(soup)

bs4.BeautifulSoup

If you go back to the **Inspect Element** window, you'll notice that if you hover over an element in the windown on the right, it will highlight on the webpage to the left. We want to retrieve all the country names in the list and the `<div id="page">` element contains all of the results that we're after, so we apply the `.find()` method to the `soup` object in order to find that element via its `id="page"` parameter.

<img src="images/div id=page.png" width="600">

In [6]:
results = soup.find(id="page")

In [7]:
results

<div id="page">
<section id="countries">
<div class="container">
<div class="row">
<div class="col-md-12">
<h1>
                            Countries of the World: A Simple Example
                            <small>250 items</small>
</h1>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-12">
<p class="lead">
                            A single page that lists information about all the countries in the world. Good for those just get started with web scraping.
                            Practice looking for patterns in the HTML that will allow you to extract information about each country. Then, build a simple web scraper that makes a request to this page, parses the HTML and prints out each country's name.
                        </p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-6">
<p>
<i class="glyphicon glyphicon-education"></i> There are <a href="/lessons/">4 video lessons</a> that show you how to scrape this page.
                        </p>
<hr/>
</div>
<div class="col-md-6 text-right">
<p>

                                Data via
                                <a class="data-attribution" href="http://peric.github.io/GetCountries/" target="_blank">http://peric.github.io/GetCountries/</a>
</p>
<hr/>
</div>
</div>
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
<strong>Population:</strong> <span class="country-population">4975593</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
<strong>Population:</strong> <span class="country-population">29121286</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ag"></i>
                            Antigua and Barbuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
<strong>Population:</strong> <span class="country-population">86754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ai"></i>
                            Anguilla
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
<strong>Population:</strong> <span class="country-population">13254</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-al"></i>
                            Albania
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
<strong>Population:</strong> <span class="country-population">2986952</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-am"></i>
                            Armenia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
<strong>Population:</strong> <span class="country-population">2968000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ao"></i>
                            Angola
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
<strong>Population:</strong> <span class="country-population">13068161</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aq"></i>
                            Antarctica
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ar"></i>
                            Argentina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
<strong>Population:</strong> <span class="country-population">41343201</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-as"></i>
                            American Samoa
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
<strong>Population:</strong> <span class="country-population">57881</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-at"></i>
                            Austria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
<strong>Population:</strong> <span class="country-population">8205000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-au"></i>
                            Australia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
<strong>Population:</strong> <span class="country-population">21515754</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-aw"></i>
                            Aruba
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
<strong>Population:</strong> <span class="country-population">71566</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ax"></i>
                            Åland
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
<strong>Population:</strong> <span class="country-population">26711</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-az"></i>
                            Azerbaijan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
<strong>Population:</strong> <span class="country-population">8303512</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ba"></i>
                            Bosnia and Herzegovina
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
<strong>Population:</strong> <span class="country-population">4590000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bb"></i>
                            Barbados
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
<strong>Population:</strong> <span class="country-population">285653</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bd"></i>
                            Bangladesh
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
<strong>Population:</strong> <span class="country-population">156118464</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-be"></i>
                            Belgium
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
<strong>Population:</strong> <span class="country-population">10403000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bf"></i>
                            Burkina Faso
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
<strong>Population:</strong> <span class="country-population">16241811</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bg"></i>
                            Bulgaria
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
<strong>Population:</strong> <span class="country-population">7148785</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bh"></i>
                            Bahrain
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
<strong>Population:</strong> <span class="country-population">738004</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bi"></i>
                            Burundi
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
<strong>Population:</strong> <span class="country-population">9863117</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bj"></i>
                            Benin
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
<strong>Population:</strong> <span class="country-population">9056010</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bl"></i>
                            Saint Barthélemy
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
<strong>Population:</strong> <span class="country-population">8450</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bm"></i>
                            Bermuda
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
<strong>Population:</strong> <span class="country-population">65365</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bn"></i>
                            Brunei
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
<strong>Population:</strong> <span class="country-population">395027</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bo"></i>
                            Bolivia
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
<strong>Population:</strong> <span class="country-population">9947418</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bq"></i>
                            Bonaire
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
<strong>Population:</strong> <span class="country-population">18012</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-br"></i>
                            Brazil
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
<strong>Population:</strong> <span class="country-population">201103330</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bs"></i>
                            Bahamas
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
<strong>Population:</strong> <span class="country-population">301790</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bt"></i>
                            Bhutan
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
<strong>Population:</strong> <span class="country-population">699847</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bv"></i>
                            Bouvet Island
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">None</span><br/>
<strong>Population:</strong> <span class="country-population">0</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bw"></i>
                            Botswana
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
<strong>Population:</strong> <span class="country-population">2029307</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-by"></i>
                            Belarus
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
<strong>Population:</strong> <span class="country-population">9685000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-bz"></i>
                            Belize
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
<strong>Population:</strong> <span class="country-population">314522</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ca"></i>
                            Canada
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
<strong>Population:</strong> <span class="country-population">33679000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
</div>
</div><!--.col-->
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cc"></i>
                            Cocos [Keeling] Islands
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
<strong>Population:</strong> <span class="country-population">628</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
</div>
</div><!--.col-->
</div><!--.row-->
<div class="row">
<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-cd"></i>
                            Democratic Republic of the Congo
                        </h3>
<div class="country-info">

As we were saying, inside the `results` object there are all the country names we're interested in, but we still need to identify them and to do that we go back to the Inspect Element window and notice that each country block has its name and all related information stored inside a `div` element with `class="col-md-4 country"`. Therefore, we apply the `.find_all()` method to the `results` object in order to get the information about each country.

In [8]:
countries = results.find_all("div", class_="col-md-4 country")

In [9]:
type(countries)

bs4.element.ResultSet

In [10]:
len(countries)

250

In [11]:
countries[0]

<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>

In [12]:
type(countries[0])

bs4.element.Tag

Now, if you look closely to the above output, you'll notice that each country name is enclosed in a `h3` tag with `class="country-name"`.

In [13]:
type(countries)

bs4.element.ResultSet

In [14]:
len(countries)

250

The output object `countries` is an iterable object of class `bs4.element.ResultSet` containing 250 elements, so we can use a for loop to print each element in the `h3` tag.

In [15]:
countries[0:3]

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>]

In [16]:
for c in countries[0:3]:
    print(c.find("h3", class_="country-name"))

<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-ae"></i>
                            United Arab Emirates
                        </h3>
<h3 class="country-name">
<i class="flag-icon flag-icon-af"></i>
                            Afghanistan
                        </h3>

As you can see, this prints everything, including the tag itself; in order **to include just the text**, we can add the `.text` attribute.

In [17]:
for c in countries[0:3]:
    print(c.find("h3", class_="country-name").text)

                            Andorra



                            United Arab Emirates



                            Afghanistan

Now, instead of printing the output to screen, it's better to append each new element to a list in order to store those information for a later use.

In [18]:
listy = []
for c in countries:
    listy.append(c.find("h3", class_="country-name").text)

In [19]:
listy[0:5]

['\n\n                            Andorra\n                        ',
 '\n\n                            United Arab Emirates\n                        ',
 '\n\n                            Afghanistan\n                        ',
 '\n\n                            Antigua and Barbuda\n                        ',
 '\n\n                            Anguilla\n                        ']

Since there are some "spaces" and "return" characters in the strings, we use the `.strip()` method to remove those from the output.

In [20]:
type(listy[0])

str

In [21]:
names = []
for c in countries:
    names.append(c.find("h3", {"class":"country-name"}).text.strip())

In [22]:
names

['Andorra',
 'United Arab Emirates',
 'Afghanistan',
 'Antigua and Barbuda',
 'Anguilla',
 'Albania',
 'Armenia',
 'Angola',
 'Antarctica',
 'Argentina',
 'American Samoa',
 'Austria',
 'Australia',
 'Aruba',
 'Åland',
 'Azerbaijan',
 'Bosnia and Herzegovina',
 'Barbados',
 'Bangladesh',
 'Belgium',
 'Burkina Faso',
 'Bulgaria',
 'Bahrain',
 'Burundi',
 'Benin',
 'Saint Barthélemy',
 'Bermuda',
 'Brunei',
 'Bolivia',
 'Bonaire',
 'Brazil',
 'Bahamas',
 'Bhutan',
 'Bouvet Island',
 'Botswana',
 'Belarus',
 'Belize',
 'Canada',
 'Cocos [Keeling] Islands',
 'Democratic Republic of the Congo',
 'Central African Republic',
 'Republic of the Congo',
 'Switzerland',
 'Ivory Coast',
 'Cook Islands',
 'Chile',
 'Cameroon',
 'China',
 'Colombia',
 'Costa Rica',
 'Cuba',
 'Cape Verde',
 'Curacao',
 'Christmas Island',
 'Cyprus',
 'Czech Republic',
 'Germany',
 'Djibouti',
 'Denmark',
 'Dominica',
 'Dominican Republic',
 'Algeria',
 'Ecuador',
 'Estonia',
 'Egypt',
 'Western Sahara',
 'Eritrea',
 'Spain',
 'Ethiopia',
 'Finland',
 'Fiji',
 'Falkland Islands',
 'Micronesia',
 'Faroe Islands',
 'France',
 'Gabon',
 'United Kingdom',
 'Grenada',
 'Georgia',
 'French Guiana',
 'Guernsey',
 'Ghana',
 'Gibraltar',
 'Greenland',
 'Gambia',
 'Guinea',
 'Guadeloupe',
 'Equatorial Guinea',
 'Greece',
 'South Georgia and the South Sandwich Islands',
 'Guatemala',
 'Guam',
 'Guinea-Bissau',
 'Guyana',
 'Hong Kong',
 'Heard Island and McDonald Islands',
 'Honduras',
 'Croatia',
 'Haiti',
 'Hungary',
 'Indonesia',
 'Ireland',
 'Israel',
 'Isle of Man',
 'India',
 'British Indian Ocean Territory',
 'Iraq',
 'Iran',
 'Iceland',
 'Italy',
 'Jersey',
 'Jamaica',
 'Jordan',
 'Japan',
 'Kenya',
 'Kyrgyzstan',
 'Cambodia',
 'Kiribati',
 'Comoros',
 'Saint Kitts and Nevis',
 'North Korea',
 'South Korea',
 'Kuwait',
 'Cayman Islands',
 'Kazakhstan',
 'Laos',
 'Lebanon',
 'Saint Lucia',
 'Liechtenstein',
 'Sri Lanka',
 'Liberia',
 'Lesotho',
 'Lithuania',
 'Luxembourg',
 'Latvia',
 'Libya',
 'Morocco',
 'Monaco',
 'Moldova',
 'Montenegro',
 'Saint Martin',
 'Madagascar',
 'Marshall Islands',
 'Macedonia',
 'Mali',
 'Myanmar [Burma]',
 'Mongolia',
 'Macao',
 'Northern Mariana Islands',
 'Martinique',
 'Mauritania',
 'Montserrat',
 'Malta',
 'Mauritius',
 'Maldives',
 'Malawi',
 'Mexico',
 'Malaysia',
 'Mozambique',
 'Namibia',
 'New Caledonia',
 'Niger',
 'Norfolk Island',
 'Nigeria',
 'Nicaragua',
 'Netherlands',
 'Norway',
 'Nepal',
 'Nauru',
 'Niue',
 'New Zealand',
 'Oman',
 'Panama',
 'Peru',
 'French Polynesia',
 'Papua New Guinea',
 'Philippines',
 'Pakistan',
 'Poland',
 'Saint Pierre and Miquelon',
 'Pitcairn Islands',
 'Puerto Rico',
 'Palestine',
 'Portugal',
 'Palau',
 'Paraguay',
 'Qatar',
 'Réunion',
 'Romania',
 'Serbia',
 'Russia',
 'Rwanda',
 'Saudi Arabia',
 'Solomon Islands',
 'Seychelles',
 'Sudan',
 'Sweden',
 'Singapore',
 'Saint Helena',
 'Slovenia',
 'Svalbard and Jan Mayen',
 'Slovakia',
 'Sierra Leone',
 'San Marino',
 'Senegal',
 'Somalia',
 'Suriname',
 'South Sudan',
 'São Tomé and Príncipe',
 'El Salvador',
 'Sint Maarten',
 'Syria',
 'Swaziland',
 'Turks and Caicos Islands',
 'Chad',
 'French Southern Territories',
 'Togo',
 'Thailand',
 'Tajikistan',
 'Tokelau',
 'East Timor',
 'Turkmenistan',
 'Tunisia',
 'Tonga',
 'Turkey',
 'Trinidad and Tobago',
 'Tuvalu',
 'Taiwan',
 'Tanzania',
 'Ukraine',
 'Uganda',
 'U.S. Minor Outlying Islands',
 'United States',
 'Uruguay',
 'Uzbekistan',
 'Vatican City',
 'Saint Vincent and the Grenadines',
 'Venezuela',
 'British Virgin Islands',
 'U.S. Virgin Islands',
 'Vietnam',
 'Vanuatu',
 'Wallis and Futuna',
 'Samoa',
 'Kosovo',
 'Yemen',
 'Mayotte',
 'South Africa',
 'Zambia',
 'Zimbabwe']

In [23]:
countries[0]

<div class="col-md-4 country">
<h3 class="country-name">
<i class="flag-icon flag-icon-ad"></i>
                            Andorra
                        </h3>
<div class="country-info">
<strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
<strong>Population:</strong> <span class="country-population">84000</span><br/>
<strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
</div>
</div>

In [24]:
int(countries[0].find("span", class_="country-population").text)

84000

In [25]:
names[0:5]

['Andorra',
 'United Arab Emirates',
 'Afghanistan',
 'Antigua and Barbuda',
 'Anguilla']

That's it, we successfully created a list including all the country names from our initial web page.

### A slightly more difficult example

At [this link](https://www.rottentomatoes.com/browse/movies_at_home/affiliates:netflix~sort:critic_highest) you will find a list of the top movies (according to the website's Tomatometer score) currently available on Netflix. We want to retrieve some information (such as the movie title) for all the movies available in the page and save such information in a pandas data frame.

We begin by sending an HTTP GET request to retrieve the HTML page and save its contents to a `BeautifulSoup` object.

*Notice the `headers={'Accept-Language': "lang=en-US"}` additional parameter, which ensures that the contents are always retrieved in english, no matter what the client language is.*

In [26]:
url = 'https://www.rottentomatoes.com/browse/movies_at_home/affiliates:netflix~sort:critic_highest'
page = requests.get(url, headers={'Accept-Language': "lang=en-US"})

In [27]:
page.status_code

200

In [28]:
soup = BeautifulSoup(page.content, "html.parser")

Using the Element Inspector tool, we can see that each movie title belongs to the `div` tag and is identified by the `class="js-tile-link"` parameter. Using the `.find_all()` method, we can find all those occurrences; we then save them to an object called `movies`.

In [29]:
movies = soup.find_all('div', class_='flex-container')

In [30]:
type(movies)

bs4.element.ResultSet

The `movies` object is a BeautifulSoup `ResultSet` object, which is an iterable and contains all the movie titles we're interested in. Let's explore the first element in the result set:

In [31]:
movies[0]

<div class="flex-container" data-ems-id="353540c1-20f4-304e-b146-f769fa105a5d">
<media-info-tile>
<poster-tile data-qa="discovery-media-list-item" media-url="/m/a_love_song_for_latasha" size-tshirt="none,xxx-large" slot="poster">
<rt-img alt="A Love Song for Latasha" class="posterImage" loading="lazy" slot="thumbnail" src="https://resizing.flixster.com/k7WNrT9Gtgyh_W9XX99OR6RGXRE=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p18702247_p_v10_aa.jpg"></rt-img>
</poster-tile>
<a class="js-tile-link" data-ems-id="353540c1-20f4-304e-b146-f769fa105a5d" data-qa="discovery-media-list-item-caption" data-track="scores" href="/m/a_love_song_for_latasha" slot="meta-data">
<score-pairs-deprecated>
<score-icon-critics certified="false" sentiment="positive" size="1" slot="criticsScoreIcon"></score-icon-critics>
<rt-text context="label" size="1" slot="criticsScore"> 100%</rt-text>
<score-icon-audience certified="false" sentiment="positive" size="1" slot="audienceScoreIcon"></score-icon-audience>
<rt-text context="label" size="1" slot="audienceScore"> 79%</rt-text>
</score-pairs-deprecated>
<rt-text data-qa="discovery-media-list-item-title" size="0.875">
          A Love Song for Latasha
        </rt-text>
<rt-text data-qa="discovery-media-list-item-start-date" size="0.75">
            Streaming Sep 24, 2020
          </rt-text>
</a>
<watchlist-button data-watchlistbuttonmanager="watchlistButton:click" ems-id="353540c1-20f4-304e-b146-f769fa105a5d" media-title="A Love Song for Latasha" media-type="Movie" slot="watchlist-button" state="unchecked">
<span slot="text">Watchlist</span>
</watchlist-button>
</media-info-tile>
</div>

We can see that each element of the `movies` object contains a series of `rt-text` tags, from which we can extract their text content. Let's use the `.find_all()` method to extract each one of these from the first element in the `movies` object:

*Note: in HTML, an `rt-text` is a custom HTML element, specific to the Rotten Tomatoes website. it is recognizable by the mandatory hyphen in its name, which is the W3C convention for custom elements.*

In [32]:
movies[0].find('rt-text')

We're interested in the second `<rt-text>` tag, as that's the one that contains the movie title, so let's use the `[2]` index to isolate it; furthermore, as we now know, to extract its text content we need to use the `.text` attribute:

In [33]:
movies[0].find_all('rt-text')

[<rt-text context="label" size="1" slot="criticsScore"> 100%</rt-text>,
 <rt-text context="label" size="1" slot="audienceScore"> 79%</rt-text>,
 <rt-text data-qa="discovery-media-list-item-title" size="0.875">
           A Love Song for Latasha
         </rt-text>,
 <rt-text data-qa="discovery-media-list-item-start-date" size="0.75">
             Streaming Sep 24, 2020
           </rt-text>]

In [34]:
movies[0].find_all('rt-text')[2]

<rt-text data-qa="discovery-media-list-item-title" size="0.875">
          A Love Song for Latasha
        </rt-text>

In [35]:
movies[0].find_all('rt-text')[2].text

'\n          A Love Song for Latasha\n        '

Applying the `.strip()` method to this result, we finally get a cleaned up version of the movie title:

In [36]:
movies[0].find_all('rt-text')[2].text.strip()

'A Love Song for Latasha'

In [37]:
movies[0].find('rt-text', {"context":"label", "slot":"audienceScore"}).text.strip()
# movies[0].find('rt-text', slot="audienceScore").text.strip()

'79%'

What we have done so far is extracting the movie title from the first element in the `movies` object. In order to **extract all the movie titles**, let's cycle through the `movies` object, extract each movie title and save it to a new list that we'll name `movie_names`:

In [38]:
movie_names = []
for m in movies:
    movie_names.append(m.find_all('rt-text')[2].text.strip())

In [39]:
movie_names[0:5]

['A Love Song for Latasha',
 'A Nonsense Christmas with Sabrina Carpenter',
 'A Random Desi Romance',
 'A Secret Love',
 'AKA']

Now, using the same method, we proceed to extract the streaming start date (which is stored in the third `<rt-text>` element):

In [40]:
movie_dates = []
for m in movies:
    movie_dates.append(m.find_all('rt-text')[3].text.strip())

In [41]:
movie_dates[0:5]

['Streaming Sep 24, 2020',
 'Streaming Dec 6, 2024',
 'Streaming Dec 16, 2015',
 'Streaming Apr 29, 2020',
 'Streaming Apr 28, 2023']

At this point, we'd like to retrieve the audience and critic scores, which are stored in the `<score-pairs-deprecated>` tag; let's use the `.find()` method to isolate this specific tag:

In [42]:
movies[0]

<div class="flex-container" data-ems-id="353540c1-20f4-304e-b146-f769fa105a5d">
<media-info-tile>
<poster-tile data-qa="discovery-media-list-item" media-url="/m/a_love_song_for_latasha" size-tshirt="none,xxx-large" slot="poster">
<rt-img alt="A Love Song for Latasha" class="posterImage" loading="lazy" slot="thumbnail" src="https://resizing.flixster.com/k7WNrT9Gtgyh_W9XX99OR6RGXRE=/206x305/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p18702247_p_v10_aa.jpg"></rt-img>
</poster-tile>
<a class="js-tile-link" data-ems-id="353540c1-20f4-304e-b146-f769fa105a5d" data-qa="discovery-media-list-item-caption" data-track="scores" href="/m/a_love_song_for_latasha" slot="meta-data">
<score-pairs-deprecated>
<score-icon-critics certified="false" sentiment="positive" size="1" slot="criticsScoreIcon"></score-icon-critics>
<rt-text context="label" size="1" slot="criticsScore"> 100%</rt-text>
<score-icon-audience certified="false" sentiment="positive" size="1" slot="audienceScoreIcon"></score-icon-audience>
<rt-text context="label" size="1" slot="audienceScore"> 79%</rt-text>
</score-pairs-deprecated>
<rt-text data-qa="discovery-media-list-item-title" size="0.875">
          A Love Song for Latasha
        </rt-text>
<rt-text data-qa="discovery-media-list-item-start-date" size="0.75">
            Streaming Sep 24, 2020
          </rt-text>
</a>
<watchlist-button data-watchlistbuttonmanager="watchlistButton:click" ems-id="353540c1-20f4-304e-b146-f769fa105a5d" media-title="A Love Song for Latasha" media-type="Movie" slot="watchlist-button" state="unchecked">
<span slot="text">Watchlist</span>
</watchlist-button>
</media-info-tile>
</div>

In [43]:
movies[0].find('score-pairs-deprecated')

<score-pairs-deprecated>
<score-icon-critics certified="false" sentiment="positive" size="1" slot="criticsScoreIcon"></score-icon-critics>
<rt-text context="label" size="1" slot="criticsScore"> 100%</rt-text>
<score-icon-audience certified="false" sentiment="positive" size="1" slot="audienceScoreIcon"></score-icon-audience>
<rt-text context="label" size="1" slot="audienceScore"> 79%</rt-text>
</score-pairs-deprecated>

You may have noticed that the `score-pairs-deprecated` tag has an attribute called `audienceScore` and one called `criticsScore`; using these two attributes, we'll be able to to extract the corresponding scores that we're interested in.

To access this information, we'll use the following combination `.find('rt-text', {'slot': 'ATTR_NAME'}).get_text(strip=True)`, where:

- the `.find()` method is used to locate the `rt-text` tags with specific `slot` attributes (`audienceScore` and `criticsScore`) ,
- the `get_text(strip=True)` method is used to get the text content without any leading or trailing whitespace.

In [44]:
movies[0].find('score-pairs-deprecated').find('rt-text', {'slot': 'audienceScore'}).get_text(strip=True)

'79%'

In [45]:
movies[0].find('score-pairs-deprecated').find('rt-text', {'slot': 'criticsScore'}).get_text(strip=True)

'100%'

Let's loop through all elements in the `movies` object to extract the audience and critics scores:

In [46]:
movie_scores_audience = []
movie_scores_critics = []
for m in movies:
    movie_scores_audience.append(m.find('score-pairs-deprecated').find('rt-text', {'slot': 'audienceScore'}).get_text(strip=True))
    movie_scores_critics.append(m.find('score-pairs-deprecated').find('rt-text', {'slot': 'criticsScore'}).get_text(strip=True))

In [47]:
movie_scores_audience[0:5]

['79%', '73%', '43%', '88%', '73%']

In [48]:
movie_scores_critics[0:5]

['100%', '100%', '100%', '100%', '100%']

Finally, let's combine together the four lists that we have created into a single DataFrame named `df_movies`:

In [49]:
df_movies = pd.DataFrame(
    {'movie_name': movie_names,
     'streaming_date': movie_dates,
     'audience_score': movie_scores_audience,
     'critics_score': movie_scores_critics
    })

In [50]:
df_movies

,movie_name,streaming_date,audience_score,critics_score
0,A Love Song for Latasha,"Streaming Sep 24, 2020",79%,100%
1,A Nonsense Christmas with Sabrina Carpenter,"Streaming Dec 6, 2024",73%,100%
2,A Random Desi Romance,"Streaming Dec 16, 2015",43%,100%
3,A Secret Love,"Streaming Apr 29, 2020",88%,100%
4,AKA,"Streaming Apr 28, 2023",73%,100%
5,Ajeeb Daastaans,"Streaming Apr 16, 2021",66%,100%
6,Ali Wong: Baby Cobra,"Streaming May 6, 2016",74%,100%
7,Ali Wong: Hard Knock Wife,"Streaming May 13, 2018",68%,100%
8,Alive and Kicking,"Streaming Apr 7, 2017",94%,100%
9,Amy Schumer: Emergency Contact,"Streaming Jun 13, 2023",14%,100%
10,Apollo 13: Survival,"Streaming Sep 5, 2024",88%,100%
11,Asoka,"Streaming Mar 17, 2017",69%,100%
12,Athlete A,"Streaming Jun 25, 2020",92%,100%
13,Audible,"Streaming Jul 1, 2021",79%,100%
14,BTS: THE RETURN,"Streaming Mar 27, 2026",,100%
15,Bitconned,"Streaming Jan 1, 2024",66%,100%
16,Blue Giant,"Streaming Apr 30, 2024",97%,100%
17,Bo Burnham: Make Happy,"Streaming Jun 3, 2016",91%,100%
18,Calibre,"Streaming Jun 29, 2018",79%,100%
19,Camp Confidential: America's Secret Nazis,"Streaming Nov 2, 2021",70%,100%
20,Catching Feelings,"Streaming May 18, 2018",58%,100%
21,Chasing Coral,"Streaming Jul 15, 2017",89%,100%
22,Chris Rock: Tamborine,"Streaming Feb 14, 2018",41%,100%
23,City of Joy,"Streaming Sep 7, 2018",71%,100%
24,Color Book,"Streaming Jun 19, 2026",,100%
25,Con Mum,"Streaming Mar 25, 2025",,
26,Creep 2,"Streaming Oct 24, 2017",72%,100%
27,Cuba and the Cameraman,"Streaming Nov 24, 2017",92%,100%

In [51]:
df_movies.shape

(28, 4)

One last thing that we can do is to clean the data frame by:

- formatting the `streaming_date` column so that it is interpreted as a date type;
- converting missing scores to a numpy NaN value (otherwise you won't be able to cast it as a float);
- remove the `%` symbol from the critics and audience scores;
- cast the two scores as integers;
- sort the data frame by the `critics_score` and then by the `audience_score`.

In [52]:
# format as a date data type
df_movies['streaming_date'] = pd.to_datetime(df_movies['streaming_date'].str.replace('Streaming ', ''))

In [54]:
# convert missing scores to a numpy NaN value
df_movies.loc[df_movies['audience_score']=='', 'audience_score'] = np.nan
df_movies.loc[df_movies['critics_score']=='', 'critics_score'] = np.nan

In [55]:
df_movies['audience_score'] = df_movies['audience_score'].str.replace('%', '')
df_movies['critics_score'] = df_movies['critics_score'].str.replace('%', '')

In [56]:
# convert the scores to floats
df_movies = df_movies.astype({'audience_score':'float', 'critics_score':'float'})

In [57]:
# check data types
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28 entries, 0 to 27
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_name      28 non-null     object
 1   streaming_date  28 non-null     datetime64[ns]
 2   audience_score  25 non-null     float64
 3   critics_score   27 non-null     float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 1.0+ KB

In [58]:
# sorting data frame
df_movies.sort_values(['critics_score', 'audience_score'], ascending = False, inplace = True)

In [59]:
df_movies

,movie_name,streaming_date,audience_score,critics_score
16,Blue Giant,2024-04-30,97.0,100.0
8,Alive and Kicking,2017-04-07,94.0,100.0
12,Athlete A,2020-06-25,92.0,100.0
27,Cuba and the Cameraman,2017-11-24,92.0,100.0
17,Bo Burnham: Make Happy,2016-06-03,91.0,100.0
21,Chasing Coral,2017-07-15,89.0,100.0
3,A Secret Love,2020-04-29,88.0,100.0
10,Apollo 13: Survival,2024-09-05,88.0,100.0
0,A Love Song for Latasha,2020-09-24,79.0,100.0
13,Audible,2021-07-01,79.0,100.0
18,Calibre,2018-06-29,79.0,100.0
6,Ali Wong: Baby Cobra,2016-05-06,74.0,100.0
1,A Nonsense Christmas with Sabrina Carpenter,2024-12-06,73.0,100.0
4,AKA,2023-04-28,73.0,100.0
26,Creep 2,2017-10-24,72.0,100.0
23,City of Joy,2018-09-07,71.0,100.0
19,Camp Confidential: America's Secret Nazis,2021-11-02,70.0,100.0
11,Asoka,2017-03-17,69.0,100.0
7,Ali Wong: Hard Knock Wife,2018-05-13,68.0,100.0
5,Ajeeb Daastaans,2021-04-16,66.0,100.0
15,Bitconned,2024-01-01,66.0,100.0
20,Catching Feelings,2018-05-18,58.0,100.0
2,A Random Desi Romance,2015-12-16,43.0,100.0
22,Chris Rock: Tamborine,2018-02-14,41.0,100.0
9,Amy Schumer: Emergency Contact,2023-06-13,14.0,100.0
14,BTS: THE RETURN,2026-03-27,NaN,100.0
24,Color Book,2026-06-19,NaN,100.0
25,Con Mum,2025-03-25,NaN,NaN

### It's your turn now

Find the easiest way to download the information of only the movies on the second [page](https://www.rottentomatoes.com/browse/movies_at_home/affiliates:netflix~sort:critic_highest?page=2). Append the newly retrieved movie titles to the df_movies data frame.

In [61]:
# get page source code
url = 'https://www.rottentomatoes.com/browse/movies_at_home/affiliates:netflix~sort:critic_highest?page=2'
page2 = requests.get(url, headers={'Accept-Language': "lang=en-US"})

page2.status_code

soup = BeautifulSoup(page2.content, "html.parser")

In [69]:
# retrieve movies information
movies = soup.find_all('div', class_='flex-container')
movies = movies[28:]  # Skip the first element which is not a movie

print(len(movies))

movie_names_page2 = []
for m in movies:
    movie_names_page2.append(m.find_all('rt-text')[2].text.strip())

print(movie_names_page2[0:5])

movie_dates_page2 = []
for m in movies:
    movie_dates_page2.append(m.find_all('rt-text')[3].text.strip())

print(movie_dates_page2[0:5])

movie_scores_audience_page2 = []
movie_scores_critics_page2 = []
for m in movies:
    movie_scores_audience_page2.append(m.find('score-pairs-deprecated').find('rt-text', {'slot': 'audienceScore'}).get_text(strip=True))
    movie_scores_critics_page2.append(m.find('score-pairs-deprecated').find('rt-text', {'slot': 'criticsScore'}).get_text(strip=True))

print(movie_scores_audience_page2[0:5])
print(movie_scores_critics_page2[0:5])

28
['Cunk on Life', 'Daughters', 'Descendant', 'End Game', 'Evelyn']
['Streaming Jan 2, 2025', 'Streaming Aug 14, 2024', 'Streaming Oct 21, 2022', 'Streaming May 4, 2018', 'Streaming Sep 10, 2019']
['81%', '91%', '64%', '75%', '75%']
['100%', '100%', '100%', '100%', '100%']

In [70]:
# create new data frame
df_movies_page2 = pd.DataFrame({
    'movie_name': movie_names_page2,
    'streaming_date': movie_dates_page2,
    'audience_score': movie_scores_audience_page2,
    'critics_score': movie_scores_critics_page2
})

df_movies_page2.head()

     movie_name          streaming_date audience_score critics_score
0  Cunk on Life   Streaming Jan 2, 2025            81%          100%
1     Daughters  Streaming Aug 14, 2024            91%          100%
2    Descendant  Streaming Oct 21, 2022            64%          100%
3      End Game   Streaming May 4, 2018            75%          100%
4        Evelyn  Streaming Sep 10, 2019            75%          100%

In [71]:
df_movies_page2['streaming_date'] = pd.to_datetime(df_movies_page2['streaming_date'].str.replace('Streaming ', ''))

df_movies_page2.loc[df_movies_page2['audience_score']=='', 'audience_score'] = np.nan
df_movies_page2.loc[df_movies_page2['critics_score']=='', 'critics_score'] = np.nan

df_movies_page2['audience_score'] = df_movies_page2['audience_score'].str.replace('%', '')
df_movies_page2['critics_score'] = df_movies_page2['critics_score'].str.replace('%', '')

df_movies_page2 = df_movies_page2.astype({'audience_score':'float', 'critics_score':'float'})

In [72]:
# check data frame shape
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
Index: 28 entries, 16 to 25
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   movie_name      28 non-null     object
 1   streaming_date  28 non-null     datetime64[ns]
 2   audience_score  25 non-null     float64
 3   critics_score   27 non-null     float64
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 1.1+ KB

In [75]:
# append new dataframe (df_movies_page2) to old one (df_movies)
df = pd.concat([df_movies, df_movies_page2], ignore_index=True)

df.head()

               movie_name streaming_date  audience_score  critics_score
0              Blue Giant     2024-04-30            97.0          100.0
1       Alive and Kicking     2017-04-07            94.0          100.0
2               Athlete A     2020-06-25            92.0          100.0
3  Cuba and the Cameraman     2017-11-24            92.0          100.0
4  Bo Burnham: Make Happy     2016-06-03            91.0          100.0

In [76]:
# sort data frame
df.sort_values(['critics_score', 'audience_score'], ascending = False, inplace = True)

In [77]:
df

,movie_name,streaming_date,audience_score,critics_score
0,Blue Giant,2024-04-30,97.0,100.0
1,Alive and Kicking,2017-04-07,94.0,100.0
41,If Anything Happens I Love You,2020-11-20,93.0,100.0
2,Athlete A,2020-06-25,92.0,100.0
3,Cuba and the Cameraman,2017-11-24,92.0,100.0
4,Bo Burnham: Make Happy,2016-06-03,91.0,100.0
29,Daughters,2024-08-14,91.0,100.0
45,John Mulaney: Kid Gorgeous at Radio City,2018-05-01,90.0,100.0
5,Chasing Coral,2017-07-15,89.0,100.0
6,A Secret Love,2020-04-29,88.0,100.0
7,Apollo 13: Survival,2024-09-05,88.0,100.0
47,Kabhi Khushi Kabhie Gham,2015-06-27,88.0,100.0
55,Lolo and the Kid,2024-08-07,88.0,100.0
51,Kingdom of Us,2017-10-13,83.0,100.0
28,Cunk on Life,2025-01-02,81.0,100.0
49,Kidnapped: Elizabeth Smart,2026-01-21,80.0,100.0
8,A Love Song for Latasha,2020-09-24,79.0,100.0
9,Audible,2021-07-01,79.0,100.0
10,Calibre,2018-06-29,79.0,100.0
33,Fanaa,2017-03-08,78.0,100.0
43,Jacqueline Novak: Get on Your Knees,2024-01-23,77.0,100.0
31,End Game,2018-05-04,75.0,100.0
32,Evelyn,2019-09-10,75.0,100.0
11,Ali Wong: Baby Cobra,2016-05-06,74.0,100.0
40,How to Rob a Bank,2024-06-05,74.0,100.0
12,A Nonsense Christmas with Sabrina Carpenter,2024-12-06,73.0,100.0
13,AKA,2023-04-28,73.0,100.0
14,Creep 2,2017-10-24,72.0,100.0
39,His House,2020-10-30,72.0,100.0
53,Life Overtakes Me,2019-06-14,72.0,100.0
15,City of Joy,2018-09-07,71.0,100.0
16,Camp Confidential: America's Secret Nazis,2021-11-02,70.0,100.0
17,Asoka,2017-03-17,69.0,100.0
18,Ali Wong: Hard Knock Wife,2018-05-13,68.0,100.0
35,Giving Voice,2020-12-11,68.0,100.0
42,Is That Black Enough for You?!?,2022-11-11,67.0,100.0
19,Ajeeb Daastaans,2021-04-16,66.0,100.0
20,Bitconned,2024-01-01,66.0,100.0
44,Jamie Foxx: What Had Happened Was...,2024-12-10,65.0,100.0
30,Descendant,2022-10-21,64.0,100.0
54,Lionheart,2019-01-04,64.0,100.0
46,John Was Trying to Contact Aliens,2020-08-21,61.0,100.0
21,Catching Feelings,2018-05-18,58.0,100.0
52,Lead Me Home,2021-11-30,57.0,100.0
34,Ghosts of Sugar Land,2019-10-16,52.0,100.0
22,A Random Desi Romance,2015-12-16,43.0,100.0
23,Chris Rock: Tamborine,2018-02-14,41.0,100.0
48,Kevin Hart: Irresponsible,2019-04-02,38.0,100.0
50,King of Clones,2023-06-23,33.0,100.0
37,Gunjan Saxena: The Kargil Girl,2020-08-13,27.0,100.0
38,Hannah Gadsby: Nanette,2018-06-19,26.0,100.0
24,Amy Schumer: Emergency Contact,2023-06-13,14.0,100.0
25,BTS: THE RETURN,2026-03-27,NaN,100.0
26,Color Book,2026-06-19,NaN,100.0
36,Grenfell: Uncovered,2025-06-20,NaN,100.0
27,Con Mum,2025-03-25,NaN,NaN