# Pandas

### Homework

Before you begin, always remember to import the necessary libraries.

In [1]:
import numpy as np
import pandas as pd

#### Standard Exercises

1. Given the follwing dictionary `sales_dict`, create a new `pandas` DataFrame from it and assign it to an object named `sales`. Show the `sales` DataFrame.

In [2]:
# do not delete this cell
sales_dict = {'categories': ['Goods', 'Services', 'Experiences'],
              'units_sold': [140, 215, 95], 
              'total_revenue': [8400, 5375, 14250],
              'cost_per_unit': [35, 10, 100]}

In [3]:
sales = pd.DataFrame(sales_dict)
sales.head()

    categories  units_sold  total_revenue  cost_per_unit
0        Goods         140           8400             35
1     Services         215           5375             10
2  Experiences          95          14250            100

2. In the cells below show the following features of the `sales` DataFrame: 

- the object's data type
- the shape
- the column's data type

In [ ]:
print(sales.info())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   categories     3 non-null      str
 1   units_sold     3 non-null      int64
 2   total_revenue  3 non-null      int64
 3   cost_per_unit  3 non-null      int64
dtypes: int64(3), str(1)
memory usage: 228.0 bytes
None
(3, 4)

In [7]:
print(sales.shape)

(3, 4)

3. Calculate the total number of `units_sold` across all categories

In [8]:
total_units_sold = sales['units_sold'].sum()
print(total_units_sold)

450

4. Add a new column to the DataFrame that multiplies `units_sold` by `cost_per_unit` and call it `total_cost`.

In [9]:
sales['total_cost'] = sales['units_sold'] * sales['cost_per_unit']
sales.head()

    categories  units_sold  total_revenue  cost_per_unit  total_cost
0        Goods         140           8400             35        4900
1     Services         215           5375             10        2150
2  Experiences          95          14250            100        9500

5. Add another column called `total_margin` where you show revenues net of costs. Then sort the dataset in descending order of `total_margin`. Which category generated the highest margins?

In [11]:
sales['total_margin'] = sales['total_revenue'] - sales['total_cost']
sales.head()

,categories,units_sold,total_revenue,cost_per_unit,total_cost,total_margin
0,Goods,140,8400,35,4900,3500
1,Services,215,5375,10,2150,3225
2,Experiences,95,14250,100,9500,4750

6. Load the `tips.csv` dataset (read a description of this dataset [here](https://vincentarelbundock.github.io/Rdatasets/doc/reshape2/tips.html)) from the `data` folder, assign it to an object called `tips` and show it to the screen.

In [14]:
tips = pd.read_csv('data/tips.csv')
tips.sample(10)

     total_bill   tip     sex smoker   day    time  size
57        26.41  1.50  Female     No   Sat  Dinner     2
225       16.27  2.50  Female    Yes   Fri   Lunch     2
185       20.69  5.00    Male     No   Sun  Dinner     5
122       14.26  2.50    Male     No  Thur   Lunch     2
75        10.51  1.25    Male     No   Sat  Dinner     2
18        16.97  3.50  Female     No   Sun  Dinner     3
174       16.82  4.00    Male    Yes   Sun  Dinner     2
50        12.54  2.50    Male     No   Sun  Dinner     2
24        19.82  3.18    Male     No   Sat  Dinner     2
184       40.55  3.00    Male    Yes   Sun  Dinner     2

7. How many observations there are for each table `sex`?

In [15]:
print(tips['sex'].value_counts())

sex
Male      157
Female     87
Name: count, dtype: int64

8. Calculate the average tip amount for males and females. Who tips the most?

In [18]:
# male tips
male_tips = tips.loc[tips['sex'] == 'Male', 'tip'].mean()
print(male_tips)

3.0896178343949043

In [19]:
# female tips
female_tips = tips.loc[tips['sex'] == 'Female', 'tip'].mean()
print(female_tips)

2.8334482758620685

9. The amount of a tip will change depending on the total amount spent for the meal, so we should look at relative values, not absolute. Create a new variable `tip_pct` that calculates the percentage of the tip relative to the total bill amount.

In [20]:
tips['tip_pct'] = tips['tip'] / tips['total_bill'] * 100
tips.head()

   total_bill   tip     sex smoker  day    time  size    tip_pct
0       16.99  1.01  Female     No  Sun  Dinner     2   5.944673
1       10.34  1.66    Male     No  Sun  Dinner     3  16.054159
2       21.01  3.50    Male     No  Sun  Dinner     3  16.658734
3       23.68  3.31    Male     No  Sun  Dinner     2  13.978041
4       24.59  3.61  Female     No  Sun  Dinner     4  14.680765

10. Calculate the average tip percentage for males and females. Who tips the most? Think about this inversion of outcome, what does it tell you?

In [22]:
# male tips
avg_male_tips = tips.loc[tips['sex'] == 'Male', 'tip_pct'].mean()
print(avg_male_tips)

15.765054700429742

In [23]:
# female tips
avg_female_tips = tips.loc[tips['sex'] == 'Female', 'tip_pct'].mean()
print(avg_female_tips)

16.649073632892478

If you want <font color='red'>**to exercise more**</font> on pandas Series and DataFrames, check out [these 101 exercises](https://www.machinelearningplus.com/python/101-pandas-exercises-python/) with (hidden) solutions *(note: the first exersises are on series, then they move to DataFrames and exersises on `.read_csv()` start from #38. Also, note that we haven't covered all of those topics yet, but if you want, you're encouraged to explore them.)*

#### Advanced Exercises

Let's reload the Google Analytics dataset that we saw in class and call it `ga` for brevity:

In [40]:
ga = pd.read_csv("data/GA Paid Search Traffic.csv", skiprows=[0,1,2,3,4,5,8], nrows=9)
ga

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,"1,051",753,"1,455",27.29%,5.62,00:03:41,0.34%,5,US$256.96
1,google merch,103,82,145,28.28%,6.04,00:03:29,2.07%,3,US$86.09
2,google backpack,95,68,121,40.50%,4.20,00:02:27,0.00%,0,US$0.00
3,Google Merchandise,93,54,147,28.57%,5.37,00:03:23,0.68%,1,US$79.98
4,Google Apparel,92,76,127,37.80%,4.97,00:03:11,0.79%,1,US$76.37
5,youtuber merch,78,76,82,78.05%,1.41,00:00:06,0.00%,0,US$0.00
6,Google Swag,63,57,80,41.25%,5.10,00:04:14,0.00%,0,US$0.00
7,google merch store,54,38,69,28.99%,5.09,00:02:33,0.00%,0,US$0.00
8,Google Clothing,39,36,49,40.82%,3.98,00:02:43,0.00%,0,US$0.00

In class we wrote the following statements to clean up the data:

In [ ]:
# DO NOT RUN

# remove comma & convert to int
ga_keywords["Users"] = ga_keywords["Users"].str.replace(',', '').astype('int64')
ga_keywords["Sessions"] = ga_keywords["Sessions"].str.replace(',', '').astype('int64')
# remove % & convert to float
ga_keywords["Bounce Rate"] = ga_keywords["Bounce Rate"].str.replace('%', '').astype('float64')
ga_keywords["E-commerce Conversion Rate"] = ga_keywords["E-commerce Conversion Rate"].str.replace('%', '').astype('float64')
# remuve US$ & convert to float
ga_keywords["Revenue"] = ga_keywords["Revenue"].str.replace('US$', '', regex=False).astype('float64')

1. Your task is to write three functions `clean_comma()`, `clean_pct()` and `clean_usd()` to solve each of the above cases, such that you can pass the `df["colname"]` as an argument to the function and reassign the result to the original column. Here are three examples of how you would use each function to clean a column: 
    - `ga["Users"] = clean_comma(ga["Users"])`
    - `ga["Bounce Rate"] = clean_pct(ga["Bounce Rate"])`
    - `ga["Revenue"] = clean_usd(ga["Revenue"])`

In [41]:
# define the function clean_comma()
def clean_comma(column):
    return column.str.replace(',', '')

In [42]:
# call the function clean_comma()
ga['Users'] = clean_comma(ga['Users'])
ga.head()

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,"1,455",27.29%,5.62,00:03:41,0.34%,5,US$256.96
1,google merch,103,82,145,28.28%,6.04,00:03:29,2.07%,3,US$86.09
2,google backpack,95,68,121,40.50%,4.20,00:02:27,0.00%,0,US$0.00
3,Google Merchandise,93,54,147,28.57%,5.37,00:03:23,0.68%,1,US$79.98
4,Google Apparel,92,76,127,37.80%,4.97,00:03:11,0.79%,1,US$76.37

In [43]:
# define the function clean_pct()
def clean_pct(column):
    return column.str.replace('%', '')

In [44]:
# call the function clean_pct()
ga['Bounce Rate'] = clean_pct(ga['Bounce Rate'])
ga.head()

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,"1,455",27.29,5.62,00:03:41,0.34%,5,US$256.96
1,google merch,103,82,145,28.28,6.04,00:03:29,2.07%,3,US$86.09
2,google backpack,95,68,121,40.50,4.20,00:02:27,0.00%,0,US$0.00
3,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68%,1,US$79.98
4,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79%,1,US$76.37

In [45]:
# define the function clean_usd()
def clean_usd(column):
    return column.str.replace('US$', '', regex=False).astype('float64')

In [46]:
# call the function clean_usd()
ga['Revenue'] = clean_usd(ga['Revenue'])
ga.head()

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,"1,455",27.29,5.62,00:03:41,0.34%,5,256.96
1,google merch,103,82,145,28.28,6.04,00:03:29,2.07%,3,86.09
2,google backpack,95,68,121,40.50,4.20,00:02:27,0.00%,0,0.00
3,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68%,1,79.98
4,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79%,1,76.37

In [51]:
# now check that the columns in the ga DataFrame have actually changed
ga.head()

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,"1,455",27.29,5.62,00:03:41,0.34%,5,256.96
1,google merch,103,82,145,28.28,6.04,00:03:29,2.07%,3,86.09
2,google backpack,95,68,121,40.50,4.20,00:02:27,0.00%,0,0.00
3,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68%,1,79.98
4,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79%,1,76.37

2. Write one function `clean_function()` that can accomplish any of the three cases from the previous point by specifying extra parameters in the function call. Here are three examples of how you would use each function to clean a column: 
    - `ga["Users"] = clean_function(ga["Users"], ',', 'int64')`
    - `ga["Bounce Rate"] = clean_function(ga["Bounce Rate"], '%', 'float64')`
    - `ga["Revenue"] = clean_function(ga["Revenue"], 'US$', 'float64')`

In [52]:
ga = pd.read_csv("data/GA Paid Search Traffic.csv", skiprows=[0,1,2,3,4,5,8], nrows=9)
ga

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,"1,051",753,"1,455",27.29%,5.62,00:03:41,0.34%,5,US$256.96
1,google merch,103,82,145,28.28%,6.04,00:03:29,2.07%,3,US$86.09
2,google backpack,95,68,121,40.50%,4.20,00:02:27,0.00%,0,US$0.00
3,Google Merchandise,93,54,147,28.57%,5.37,00:03:23,0.68%,1,US$79.98
4,Google Apparel,92,76,127,37.80%,4.97,00:03:11,0.79%,1,US$76.37
5,youtuber merch,78,76,82,78.05%,1.41,00:00:06,0.00%,0,US$0.00
6,Google Swag,63,57,80,41.25%,5.10,00:04:14,0.00%,0,US$0.00
7,google merch store,54,38,69,28.99%,5.09,00:02:33,0.00%,0,US$0.00
8,Google Clothing,39,36,49,40.82%,3.98,00:02:43,0.00%,0,US$0.00

In [53]:
# define the function clean_function()
def clean_function(column, target_char, target_dtype):
    return column.str.replace(target_char, '', regex=False).astype(target_dtype)

In [54]:
# call the function clean_function()
ga["Users"] = clean_function(ga["Users"], ',', 'int64')
ga["Bounce Rate"] = clean_function(ga["Bounce Rate"], '%', 'float64')
ga["Revenue"] = clean_function(ga["Revenue"], 'US$', 'float64')

In [56]:
# now check that the columns in the ga DataFrame have actually changed
ga

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,"1,455",27.29,5.62,00:03:41,0.34%,5,256.96
1,google merch,103,82,145,28.28,6.04,00:03:29,2.07%,3,86.09
2,google backpack,95,68,121,40.50,4.20,00:02:27,0.00%,0,0.00
3,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68%,1,79.98
4,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79%,1,76.37
5,youtuber merch,78,76,82,78.05,1.41,00:00:06,0.00%,0,0.00
6,Google Swag,63,57,80,41.25,5.10,00:04:14,0.00%,0,0.00
7,google merch store,54,38,69,28.99,5.09,00:02:33,0.00%,0,0.00
8,Google Clothing,39,36,49,40.82,3.98,00:02:43,0.00%,0,0.00