# Pandas

### Introduction to Pandas

`pandas` is a Python library for **data manipulation and analysis**. It offers data structures and operations for manipulating numerical tables and time series. The name is derived from the term "**pan**el **da**ta" (a term for data sets that include observations over multiple time periods for the same observations). **Wes McKinney** started building what would become pandas from 2007 to 2013; it has been an entirely community-managed project since then.

I would also recommend you to check out his **book on data analysis with Python**, which is freely available online at this link: [Python for Data Analysis](https://wesmckinney.com/book/).

<figure>
<img src="img/wes-hadley.jpeg" alt="fishy" class="bg-primary mb-1" width="400">
<figcaption align = "center"> Hadley Wickham (R > Tidyverse) & Wes McKinney (Py > pandas) </figcaption>
</figure>

While pandas adopts many coding idioms from NumPy, the biggest difference is that **pandas is designed for working with tabular or heterogeneous data** (that is: numbers, dates, strings, ...). NumPy, by contrast, is best suited for working with homogeneously-typed numerical array data (that is: numbers).

Just like numpy is conventionally imported as `import numpy as np`, pandas has its own convention:

In [1]:
import pandas as pd
import numpy as np

`pandas` provides two **data structures** that allow you to shape data into a readable form:

- **Series**: it's a one-dimensional array-like object containing a sequence of values
- **Data Frames**: it's a rectangular table of data where each column is a Series

So the Series is the data structure for a single column of a DataFrame not only conceptually, but literally; in fact, the data in a DataFrame is effectively stored in memory as a collection of Series.

#### Series

A pandas `series` is a **one-dimensional data structure** that comprises of a key-value pair. It contains a sequence of values of the same type and an associated array of data labels, called its index (these are the keys of the key-value pair). 

You can initialise a simple series with `pd.Series()`:

In [2]:
# integer series
pd.Series([2, -5, 4, 7])

0    2
1   -5
2    4
3    7
dtype: int64

In [3]:
# float series
pd.Series([3.0, 3.5, 4.0, 4.5, 5.0])

0    3.0
1    3.5
2    4.0
3    4.5
4    5.0
dtype: float64

In [4]:
# string series
pd.Series(["junior", "adult", "senior"])

0    junior
1     adult
2    senior
dtype: object

We said that a series is a collection of a key-values pairs (similar to a Python dictionary); you can access these elements via the `.index` and `.array` attributes:

In [5]:
# initialise a series "s"
s = pd.Series([10, 20, 30, 40, 50])

In [7]:
# get the keys (index) of the series 
s.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
# get the values of the series
s.array

<PandasArray>
[10, 20, 30, 40, 50]
Length: 5, dtype: int64

You can also specify the keys/index of the series via a specific value or character:

In [7]:
# initialise a series "s2"
s2 = pd.Series(["junior", "adult", "senior"], index=["j", "a", "s"])
s2

j    junior
a     adult
s    senior
dtype: object

In [8]:
# get the keys (index) of the series 
s2.index

Index(['j', 'a', 's'], dtype='object')

In [12]:
# get the values of the series
s2.values

array(['junior', 'adult', 'senior'], dtype=object)

In [13]:
s2.array

<NumpyExtensionArray>
['junior', 'adult', 'senior']
Length: 3, dtype: object

Indexing, slicing, assignment and boolean masking work in an analogous way to Python lists and numpy's arrays:

In [10]:
# slicing by index value
s[1:3]

1    20
2    30
dtype: int64

In [11]:
# overwrite an existing value
s[4] = 60
s

0    10
1    20
2    30
3    40
4    60
dtype: int64

In [14]:
# boolean masking
s[s > 30]

3    40
4    60
dtype: int64

In [15]:
s2

j    junior
a     adult
s    senior
dtype: object

In [16]:
# slicing by single index value
s2["a"]

'adult'

In [17]:
# slicing by multiple index values (notice the double square brackets)
s2[["a", "s"]]

a     adult
s    senior
dtype: object

In [18]:
# multiplying by a scalar
s3 = s * 10
s3

0    100
1    200
2    300
3    400
4    600
dtype: int64

You can transform a dictionary into a Series (and a Series can be converted back to a dictionary with the `.to_dict()` method):

In [19]:
# given the following dictionary...
cities = {"Rome":2761632, "Milan":1371498, "Naples":914758, "Turin":848885, "Palermo":np.nan}
cities

{'Rome': 2761632,
 'Milan': 1371498,
 'Naples': 914758,
 'Turin': 848885,
 'Palermo': nan}

In [20]:
# ...we can create a Series: 
cities_s = pd.Series(cities)
cities_s

Rome       2761632.0
Milan      1371498.0
Naples      914758.0
Turin       848885.0
Palermo          NaN
dtype: float64

The functions `pd.isna()` and `pd.notna()` can be used to detect missing data:

In [21]:
# detect missing values
pd.isna(cities_s)

Rome       False
Milan      False
Naples     False
Turin      False
Palermo     True
dtype: bool

A function like `pd.isna()` can be used as a boolean mask to get a subselection of the Series. Here we select the miising value and assign it the correct value:

In [22]:
# pd.isna() boolean mask + assignment of new value
cities_s[pd.isna(cities_s)] = 630828
cities_s

Rome       2761632.0
Milan      1371498.0
Naples      914758.0
Turin       848885.0
Palermo     630828.0
dtype: float64

#### Data Frame

A pandas `DataFrame` is a **two-dimensional data-structure** that can be thought of as a spreadsheet. A DataFrame can also be thought of as a **dictionary of Series**. The DataFrame has both a **row and column index** and each column can be of a **different data type** (numeric, string, boolean, etc.)

The most common way to **create a pandas DataFrame** is from a dictionary of equal-length lists or NumPy arrays:

In [18]:
data = {"gender": ["Males", "Males", "Males", "Males", "Females", "Females", "Females", "Females"],
        "year": [2018, 2019, 2020, 2021, 2018, 2019, 2020, 2021],
        "popM": [29.428, 29.131, 29.050, 28.866, 31.056, 30.685, 30.591, 30.370]}
frame = pd.DataFrame(data)
frame

    gender  year    popM
0    Males  2018  29.428
1    Males  2019  29.131
2    Males  2020  29.050
3    Males  2021  28.866
4  Females  2018  31.056
5  Females  2019  30.685
6  Females  2020  30.591
7  Females  2021  30.370

In [21]:
frame['gender'].values

array(['Males', 'Males', 'Males', 'Males', 'Females', 'Females',
       'Females', 'Females'], dtype=object)

You can access the first / last rows of your dataframe with the `.head()` and `.tail()` methods:

In [23]:
# top 5 rows (5 is the default)
frame.head(2)

  gender  year    popM
0  Males  2018  29.428
1  Males  2019  29.131

In [25]:
frame.sample(5)

    gender  year    popM
6  Females  2020  30.591
2    Males  2020  29.050
0    Males  2018  29.428
3    Males  2021  28.866
7  Females  2021  30.370

In [24]:
# last 3 rows 
frame.tail(3)

    gender  year    popM
5  Females  2019  30.685
6  Females  2020  30.591
7  Females  2021  30.370

You can **retrieve a column in a DataFrame** as a Series with the following two methods: 

- `frame["colname"]` indexing or square bracket access *(preferred method)*
- `frame.colname` attribute or dot access

In [27]:
# retrieve the popM column with the dict-like notation
frame["popM"]

0    29.428
1    29.131
2    29.050
3    28.866
4    31.056
5    30.685
6    30.591
7    30.370
Name: popM, dtype: float64

In [28]:
# retrieve the popM column with the dot-attribute notation
frame.popM

0    29.428
1    29.131
2    29.050
3    28.866
4    31.056
5    30.685
6    30.591
7    30.370
Name: popM, dtype: float64

Some notes on the **differences between the two** access methods: 

- indexing `[]` (squared brackets access) has the full functionaly to operate on DataFrame column data
- attribute access (dot access) is mainly for convinience to access existing DataFrame column data, but some limitations, namely: 
    - you cannot add a column with this method
    - it only works if the column name does not conflict with any of the method names in DataFrame
    - it won't work if you have spaces in the column name 
    - it won't work if the column name is an integer

Check the [documentation](http://pandas-docs.github.io/pandas-docs-travis/user_guide/indexing.html#attribute-access) for more on attribute access.

**Rows can also be retrieved** by index position `.iloc` or by index name `.loc`. Let's first **set a new index** on our dataframe with the `.set_index()` method so to better understand the difference between these two ways of slicing our data.

In [28]:
# to set a new index on our dataframe
frame.set_index([["m18", "m19", "m20", "m21", "f18", "f19", "f20", "f21"]], inplace=True)
frame

      gender  year    popM
m18    Males  2018  29.428
m19    Males  2019  29.131
m20    Males  2020  29.050
m21    Males  2021  28.866
f18  Females  2018  31.056
f19  Females  2019  30.685
f20  Females  2020  30.591
f21  Females  2021  30.370

Using `.iloc[2]`, we will select the row at **index** = 2 (so the third row, since Python indexes start at 0):

In [29]:
# the i in iloc stands for index, so this will retrieve the row at index = 2
frame.iloc[2]

gender    Males
year       2020
popM      29.05
Name: m20, dtype: object

Using `.loc["f18"]`, we will select the row whose **index name** = "f18" (so the fifth row in this example):

In [30]:
# the loc will match the index value, so this will retrieve the row with an index value of 2
frame.loc["f18"]

gender    Females
year         2018
popM       31.056
Name: f18, dtype: object

*Check [this table](https://wesmckinney.com/book/pandas-basics.html#tbl-table_dataframe_loc_iloc) for a complete list of indexing solutions.*

To **create a new column**, you can use the same indexing / square bracket access that we saw before:

In [29]:
frame

    gender  year    popM
0    Males  2018  29.428
1    Males  2019  29.131
2    Males  2020  29.050
3    Males  2021  28.866
4  Females  2018  31.056
5  Females  2019  30.685
6  Females  2020  30.591
7  Females  2021  30.370

In [30]:
frame['country'] = 'Italy'
frame['constant'] = 999
frame['variable'] = np.arange(8)
frame['random'] = np.random.rand(8) * 100
frame

    gender  year    popM country  constant  variable     random
0    Males  2018  29.428   Italy       999         0  92.970273
1    Males  2019  29.131   Italy       999         1  68.495515
2    Males  2020  29.050   Italy       999         2  10.475720
3    Males  2021  28.866   Italy       999         3  52.270372
4  Females  2018  31.056   Italy       999         4  23.049044
5  Females  2019  30.685   Italy       999         5  82.725341
6  Females  2020  30.591   Italy       999         6   7.814698
7  Females  2021  30.370   Italy       999         7  37.357385

You can also multiply one column by the other and save it as a new column:

In [31]:
frame["new"] = frame["variable"] * frame["random"]
frame

    gender  year    popM country  constant  variable     random         new
0    Males  2018  29.428   Italy       999         0  92.970273    0.000000
1    Males  2019  29.131   Italy       999         1  68.495515   68.495515
2    Males  2020  29.050   Italy       999         2  10.475720   20.951440
3    Males  2021  28.866   Italy       999         3  52.270372  156.811117
4  Females  2018  31.056   Italy       999         4  23.049044   92.196175
5  Females  2019  30.685   Italy       999         5  82.725341  413.626707
6  Females  2020  30.591   Italy       999         6   7.814698   46.888190
7  Females  2021  30.370   Italy       999         7  37.357385  261.501698

To **retrieve the column names** use the `.columns` attribute:

In [32]:
frame.columns

Index(['gender', 'year', 'popM', 'country', 'constant', 'variable', 'random',
       'new'],
      dtype='object')

Similarly, use the `.index` attribute to **retrieve the index names**:

In [33]:
frame.index

RangeIndex(start=0, stop=8, step=1)

To **change the order of the variables** you can rearrange the column names in the following way: 

*(Note: omitting a name in the square brackets will automatically drop that column)*

In [34]:
frame = frame[['country', 'gender', 'year', 'popM', 'random']]
frame

  country   gender  year    popM     random
0   Italy    Males  2018  29.428  92.970273
1   Italy    Males  2019  29.131  68.495515
2   Italy    Males  2020  29.050  10.475720
3   Italy    Males  2021  28.866  52.270372
4   Italy  Females  2018  31.056  23.049044
5   Italy  Females  2019  30.685  82.725341
6   Italy  Females  2020  30.591   7.814698
7   Italy  Females  2021  30.370  37.357385

To **delete a column** use the `.drop()` method and specifying the column `axis = 1` *(notice that with `axis = 0` you can delete specific rows by selecting the relative index name)*:

In [35]:
frame = frame.drop(["random"], axis = 1)
frame

  country   gender  year    popM
0   Italy    Males  2018  29.428
1   Italy    Males  2019  29.131
2   Italy    Males  2020  29.050
3   Italy    Males  2021  28.866
4   Italy  Females  2018  31.056
5   Italy  Females  2019  30.685
6   Italy  Females  2020  30.591
7   Italy  Females  2021  30.370

You can use **boolean conditions** to keep just a slice of the dataset:

In [42]:
frame[frame["gender"] == "Males"]

  country gender  year    popM
0   Italy  Males  2018  29.428
1   Italy  Males  2019  29.131
2   Italy  Males  2020  29.050
3   Italy  Males  2021  28.866

And, by placing another square bracket slicer next to the first one, you can select a specific column:

In [43]:
frame[frame["gender"] == "Males"]["popM"]

0    29.428
1    29.131
2    29.050
3    28.866
Name: popM, dtype: float64

To **sort the DataFrame by the values of a column**, use the `.sort_values()` method specifying the column name like this:

In [44]:
frame.sort_values("popM")

  country   gender  year    popM
3   Italy    Males  2021  28.866
2   Italy    Males  2020  29.050
1   Italy    Males  2019  29.131
0   Italy    Males  2018  29.428
7   Italy  Females  2021  30.370
6   Italy  Females  2020  30.591
5   Italy  Females  2019  30.685
4   Italy  Females  2018  31.056

To sort in descending order add the `ascending=False` parameter:

In [45]:
frame.sort_values("popM", ascending=False)

  country   gender  year    popM
4   Italy  Females  2018  31.056
5   Italy  Females  2019  30.685
6   Italy  Females  2020  30.591
7   Italy  Females  2021  30.370
0   Italy    Males  2018  29.428
1   Italy    Males  2019  29.131
2   Italy    Males  2020  29.050
3   Italy    Males  2021  28.866

To sort multiple columns, include the column names (and the ascending parameter, if necessary) in the square brackets:

In [46]:
frame.sort_values(["gender", "year"], ascending = [True, False])

  country   gender  year    popM
7   Italy  Females  2021  30.370
6   Italy  Females  2020  30.591
5   Italy  Females  2019  30.685
4   Italy  Females  2018  31.056
3   Italy    Males  2021  28.866
2   Italy    Males  2020  29.050
1   Italy    Males  2019  29.131
0   Italy    Males  2018  29.428

You can compute descriptive statistics using the `.sum()`, `.mean()`, `.cumsum()` (and many more) methods:

In [49]:
print(frame["gender"].min())
print(frame["popM"].mean())
print(frame["popM"].sum())
print(frame["popM"].max())

Females
29.897125
239.177
31.056

In [50]:
# you can compute the cumulative sum with .cumsum()
frame["ones"] = 1
frame["cumsum"] = frame["ones"].cumsum()
frame

  country   gender  year    popM  ones  cumsum
0   Italy    Males  2018  29.428     1       1
1   Italy    Males  2019  29.131     1       2
2   Italy    Males  2020  29.050     1       3
3   Italy    Males  2021  28.866     1       4
4   Italy  Females  2018  31.056     1       5
5   Italy  Females  2019  30.685     1       6
6   Italy  Females  2020  30.591     1       7
7   Italy  Females  2021  30.370     1       8

The `describe()` method allows you to create a **table of descriptive statistics** about the numerical columns in your dataset:

In [51]:
frame.describe(include='all')

       country gender         year       popM  ones   cumsum
count        8      8     8.000000   8.000000   8.0  8.00000
unique       1      2          NaN        NaN   NaN      NaN
top      Italy  Males          NaN        NaN   NaN      NaN
freq         8      4          NaN        NaN   NaN      NaN
mean       NaN    NaN  2019.500000  29.897125   1.0  4.50000
std        NaN    NaN     1.195229   0.866576   0.0  2.44949
min        NaN    NaN  2018.000000  28.866000   1.0  1.00000
25%        NaN    NaN  2018.750000  29.110750   1.0  2.75000
50%        NaN    NaN  2019.500000  29.899000   1.0  4.50000
75%        NaN    NaN  2020.250000  30.614500   1.0  6.25000
max        NaN    NaN  2021.000000  31.056000   1.0  8.00000

In [53]:
frame.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  8 non-null      object
 1   gender   8 non-null      object
 2   year     8 non-null      int64
 3   popM     8 non-null      float64
 4   ones     8 non-null      int64
 5   cumsum   8 non-null      int64
dtypes: float64(1), int64(3), object(2)
memory usage: 516.0+ bytes

Check out [this table](https://wesmckinney.com/book/pandas-basics.html#tbl-table_descriptive_stats) for a list of more statistical functions you can use with Series and DataFrames.

Finally, if you need to find out the unique elements in a Column or if you want to count the occurrences of a category within a column, you can use the `.unique()` and `.value_counts()` methods, respectively:

In [54]:
# to enumerate the unique values in a DataFrame column: 
frame["year"].unique()

array([2018, 2019, 2020, 2021])

In [55]:
# to count the occurrences of each category in a DataFrame column: 
frame["gender"].value_counts()

gender
Males      4
Females    4
Name: count, dtype: int64

---

### Command Line 101

#### Unix (Mac OS / Linux)

- Open a Terminal in the **3.11.27 Pandas** folder (check [this tutorial](https://www.maketecheasier.com/launch-terminal-current-folder-mac/) for a refresher) 
- Use the command `ls` to check the contents of the directory
- Use the command `cd data` to move into the **data** folder *(cd = change directory)*
- Use the command `echo "hello world" > file.txt` to create a new file **file.txt** and write the string **hello world** inside it
- Use the command `cat file.txt` to check the contents of the file
- Use the command `wc -l file.txt` to count the number of rows in the file

Check out [this page](https://www.earthdatascience.org/courses/intro-to-earth-data-science/open-reproducible-science/bash/bash-commands-to-manage-directories-files/) and [this video](https://www.youtube.com/watch?v=SgGFZvlqcwk) for more useful commands on how to work with files and dierctories.

#### Windows

*Note: Windows users with Windows 10 or higher can [activate the Windows Subsystem for Linux (WSL)](https://www.laptopmag.com/articles/use-bash-shell-windows-10), which will enable the Linux Bash Shell in Windows 10.*

- Open a Command Prompt in the **3.11.27 Pandas** folder (check [this tutorial](https://www.lifewire.com/open-command-prompt-in-a-folder-5185505) for a refresher) 
- Use the command `dir` to check the contents of the directory
- Use the command `cd data` to move into the **data** folder *(cd = change directory)*
- Use the command `echo hello world > file.txt` to create a new file **file.txt** and write the string **hello world** inside it
- Use the command `type file.txt` to check the contents of the file
- Use the command `find /v /c "" file.txt` to count the number of rows in the file

Check out this [list of commands](https://www.ionos.com/digitalguide/server/know-how/windows-cmd-commands/) as well as these videos on [navigating the file system](https://www.youtube.com/watch?v=9zMWXD-xoxc) and [working with files](https://www.youtube.com/watch?v=tqdiGfF68cc).

---

### Reading data in

There are plenty of [pandas functions for reading tabular data](https://wesmckinney.com/book/accessing-data.html#tbl-table_parsing_functions) as a DataFrame; one of the most frequently used is `pd.read_csv` which has a long list of optional parameters that can help you deal with exceptions and messy data in the data loading process. Nevertheless, if your dataset is fairly clean, you can load a .csv file in one line of code, just like in the following example. 

Let's load the **iris** dataset, which is a very famous dataset among statisticians, it was introduced by the British statistician and biologist Ronald Fisher in 1936. 

The data set consists of 50 samples from each of **three species of Iris** (setosa, virginica and versicolor) for a total of 150 observations. Four features were measured from each sample: the **length and the width of the sepals and petals**, in centimeters. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species from each other.

Before loading the dataset, let's quickly inspect it and check the number of records using the command line:

In [48]:
# unix:
!wc -l data/iris.csv
# windows:
#find /v /c "" data\iris.txt

     150 data/iris.csv

In [49]:
# unix: 
!head -5 data/iris.csv   # head is like cat but shows only first -n rows
# windows:
#type data\iris.txt

"sepal.length","sepal.width","petal.length","petal.width","variety"
5.1,3.5,1.4,.2,"Setosa"
4.9,3,1.4,.2,"Setosa"
4.7,3.2,1.3,.2,"Setosa"
4.6,3.1,1.5,.2,"Setosa"

In [69]:
# read the data and save it to an DataFrame object
iris = pd.read_csv("data/tips.csv", sep=",")

In [70]:
# let's check the data type of object iris
type(iris)

pandas.core.frame.DataFrame

In [71]:
# let's check its number of rows and columns
iris.shape

(244, 7)

In [74]:
# let's print the first five rows of the data
iris.sample(5)

     total_bill   tip     sex smoker   day    time  size
70        12.02  1.97    Male     No   Sat  Dinner     2
124       12.48  2.52  Female     No  Thur   Lunch     2
148        9.78  1.73    Male     No  Thur   Lunch     2
169       10.63  2.00  Female    Yes   Sat  Dinner     2
200       18.71  4.00    Male    Yes  Thur   Lunch     3

Let's check how many observations we have for each `variety`:

In [75]:
iris["time"].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

Let's say we're interested in the average `petal.length` for each variety, therefore we'll be interested in this portion of the dataset:

In [55]:
iris.loc[:,["petal.length","variety"]]

     petal.length    variety
0             1.4     Setosa
1             1.4     Setosa
2             1.3     Setosa
3             1.5     Setosa
4             1.4     Setosa
..            ...        ...
145           5.2  Virginica
146           5.0  Virginica
147           5.2  Virginica
148           5.4  Virginica
149           5.1  Virginica

[150 rows x 2 columns]

We can filter the dataset so to keep just the rows of the Setosa variety in the following way:

In [56]:
iris.loc[iris["variety"]=="Setosa",["petal.length","variety"]].head()

   petal.length variety
0           1.4  Setosa
1           1.4  Setosa
2           1.3  Setosa
3           1.5  Setosa
4           1.4  Setosa

At this point, I can calculate the average petal length by simply taking the average of the `petal.length` column:

In [57]:
iris.loc[iris["variety"]=="Setosa","petal.length"].mean()

1.4620000000000002

In [58]:
print("Avg. petal length by iris variety:")
print("Setosa:", iris.loc[iris["variety"]=="Setosa"]["petal.length"].mean())
print("Versicolor:", iris.loc[iris["variety"]=="Versicolor"]["petal.length"].mean())
print("Virginica:", iris.loc[iris["variety"]=="Virginica"]["petal.length"].mean())

Avg. petal length by iris variety:
Setosa: 1.4620000000000002
Versicolor: 4.26
Virginica: 5.552

In [59]:
print("Avg. petal length by iris variety:")
for var in iris["variety"].unique(): 
    print(var, ":", iris.loc[iris["variety"]==var]["petal.length"].mean())

Avg. petal length by iris variety:
Setosa : 1.4620000000000002
Versicolor : 4.26
Virginica : 5.552

Let's see how to **load a slightly messier dataset**. You can find the `GA Paid Search Traffic.csv` file in the `data` folder, which was generated and downloaded from the **Paid Keyword report** in the **Google Analytics** account of the Google Merchandise Store: *Acquisition > Campaigns > Paid Keywords*. 

By inspecting the dataset via the command line *(hint: you can also double-click the dataset in the File Browser panel on the left)* we notice that there are three main blocks of information: 

- a header containing some metadata information 
- a first block of data related to paid keyword performance
- a second block of data containing a time series with the number of users

In [60]:
!cat data/GA\ Paid\ Search\ Traffic.csv

# ----------------------------------------
# 1 Master View
# Paid Search Traffic
# 20190501-20190531
# ----------------------------------------

Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
Google Merchandise Store,"1,051",753,"1,455",27.29%,5.62,00:03:41,0.34%,5,US$256.96
(not set),546,346,759,29.78%,5.32,00:03:18,0.13%,1,US$12.99
google merch,103,82,145,28.28%,6.04,00:03:29,2.07%,3,US$86.09
google backpack,95,68,121,40.50%,4.20,00:02:27,0.00%,0,US$0.00
Google Merchandise,93,54,147,28.57%,5.37,00:03:23,0.68%,1,US$79.98
Google Apparel,92,76,127,37.80%,4.97,00:03:11,0.79%,1,US$76.37
youtuber merch,78,76,82,78.05%,1.41,00:00:06,0.00%,0,US$0.00
Google Swag,63,57,80,41.25%,5.10,00:04:14,0.00%,0,US$0.00
google merch store,54,38,69,28.99%,5.09,00:02:33,0.00%,0,US$0.00
Google Clothing,39,36,49,40.82%,3.98,00:02:43,0.00%,0,US$0.00
,"2,539","1,853","3,457",32.51%,5.21,00:03:17,0.40%,14,US$607.60

Day Index,Users
01/05/2019,93
02/05/2019,114
03/05/2019,121
04/05/2019,69
05/05/2019,75
06/05/2019,109
07/05/2019,140
08/05/2019,148
09/05/2019,167
10/05/2019,135
11/05/2019,80
12/05/2019,60
13/05/2019,149
14/05/2019,117
15/05/2019,107
16/05/2019,116
17/05/2019,101
18/05/2019,65
19/05/2019,63
20/05/2019,58
21/05/2019,15
22/05/2019,61
23/05/2019,122
24/05/2019,114
25/05/2019,84
26/05/2019,118
27/05/2019,126
28/05/2019,142
29/05/2019,64
30/05/2019,16
31/05/2019,15
,"2,964"

If we try to read the file as is, we will get an error, line in the block below:

In [61]:
# read the data and save it to an DataFrame object
pd.read_csv("data/GA Paid Search Traffic.csv")

ParserError: Error tokenizing data. C error: Expected 1 fields in line 7, saw 10

Let's refer back to the [documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) of the `pd.read_csv()` function to see which parameters could come in handy here. In particular the following two paramenters will help us deal with this file:

- **skiprows**: number of lines to skip (int) at the start of the file
- **nrows**: number of rows of file to read

In [62]:
ga_keywords = pd.read_csv("data/GA Paid Search Traffic.csv", skiprows=5, nrows=10)
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,"1,051",753,"1,455",27.29%,5.62,00:03:41,0.34%,5,US$256.96
1,(not set),546,346,759,29.78%,5.32,00:03:18,0.13%,1,US$12.99
2,google merch,103,82,145,28.28%,6.04,00:03:29,2.07%,3,US$86.09
3,google backpack,95,68,121,40.50%,4.20,00:02:27,0.00%,0,US$0.00
4,Google Merchandise,93,54,147,28.57%,5.37,00:03:23,0.68%,1,US$79.98
5,Google Apparel,92,76,127,37.80%,4.97,00:03:11,0.79%,1,US$76.37
6,youtuber merch,78,76,82,78.05%,1.41,00:00:06,0.00%,0,US$0.00
7,Google Swag,63,57,80,41.25%,5.10,00:04:14,0.00%,0,US$0.00
8,google merch store,54,38,69,28.99%,5.09,00:02:33,0.00%,0,US$0.00
9,Google Clothing,39,36,49,40.82%,3.98,00:02:43,0.00%,0,US$0.00

It's always important to **check the data type of the DataFrame's columns** after loading the data; you always want to ensure that the data has been imported as expected. You can use the `.dtype` attribute or the `.info()` method on the DataFrame to get a table showing the data type for each column of the DataFrame. 

*Notice that the `object` data type is a string.* 

Check out the table below for a more [detailed explanation](https://pbpython.com/pandas_dtypes.html) of data types in `pandas`: 

<img src="img/pandas-dtypes.png" width="600">

Let's check the data type of each column of the `ga_keywords` DataFrame using the `.info()` method:

In [63]:
ga_keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Keyword                     10 non-null     object
 1   Users                       10 non-null     object
 2   New Users                   10 non-null     int64
 3   Sessions                    10 non-null     object
 4   Bounce Rate                 10 non-null     object
 5   Pages/Session               10 non-null     float64
 6   Avg. Session Duration       10 non-null     object
 7   E-commerce Conversion Rate  10 non-null     object
 8   Transactions                10 non-null     int64
 9   Revenue                     10 non-null     object
dtypes: float64(1), int64(2), object(7)
memory usage: 928.0+ bytes

The verdict is that some columns have been interpreted correctly, others not so much; I'll report just the changes that need to be done: 

- **Users** & **Sessions** --> remove the "," sign & convert from string to int
- **Bounce Rate** & **E-commerce Conversion Rate** --> remove % sign & convert from string to float
- **Revenue** --> remove US$ sign & convert from string to float

Let's start with Users & Sessions. The issue here is that the `,`, which represents the thousands separator, is making Python think that this is a string and not an integer, so we'll need to use the `.replace()` method to find a `,` and replace it with nothing:

In [ ]:
ga_keywords["Users"] = ga_keywords["Users"].str.replace(',', '').astype('int64')

0    1051
1     546
2     103
3      95
4      93
5      92
6      78
7      63
8      54
9      39
Name: Users, dtype: int64

In [65]:
# remove comma & convert to int
ga_keywords["Users"] = ga_keywords["Users"].str.replace(',', '').astype('int64')
ga_keywords["Sessions"] = ga_keywords["Sessions"].str.replace(',', '').astype('int64')
# remove % & convert to float
ga_keywords["Bounce Rate"] = ga_keywords["Bounce Rate"].str.replace('%', '').astype('float64')
ga_keywords["E-commerce Conversion Rate"] = ga_keywords["E-commerce Conversion Rate"].str.replace('%', '').astype('float64')
# remuve US$ & convert to float
ga_keywords["Revenue"] = ga_keywords["Revenue"].str.replace('US$', '', regex=False).astype('float64')

In [66]:
ga_keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Keyword                     10 non-null     object
 1   Users                       10 non-null     int64
 2   New Users                   10 non-null     int64
 3   Sessions                    10 non-null     int64
 4   Bounce Rate                 10 non-null     float64
 5   Pages/Session               10 non-null     float64
 6   Avg. Session Duration       10 non-null     object
 7   E-commerce Conversion Rate  10 non-null     float64
 8   Transactions                10 non-null     int64
 9   Revenue                     10 non-null     float64
dtypes: float64(4), int64(4), object(2)
memory usage: 928.0+ bytes

In [67]:
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,1455,27.29,5.62,00:03:41,0.34,5,256.96
1,(not set),546,346,759,29.78,5.32,00:03:18,0.13,1,12.99
2,google merch,103,82,145,28.28,6.04,00:03:29,2.07,3,86.09
3,google backpack,95,68,121,40.50,4.20,00:02:27,0.00,0,0.00
4,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68,1,79.98
5,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79,1,76.37
6,youtuber merch,78,76,82,78.05,1.41,00:00:06,0.00,0,0.00
7,Google Swag,63,57,80,41.25,5.10,00:04:14,0.00,0,0.00
8,google merch store,54,38,69,28.99,5.09,00:02:33,0.00,0,0.00
9,Google Clothing,39,36,49,40.82,3.98,00:02:43,0.00,0,0.00

We see a `(not set)` keyword, which is not that meaningful to us, so we decide to remove it from our dataset using a boolean mask:

In [68]:
ga_keywords = ga_keywords[ga_keywords["Keyword"] != "(not set)"]
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,1455,27.29,5.62,00:03:41,0.34,5,256.96
2,google merch,103,82,145,28.28,6.04,00:03:29,2.07,3,86.09
3,google backpack,95,68,121,40.50,4.20,00:02:27,0.00,0,0.00
4,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68,1,79.98
5,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79,1,76.37
6,youtuber merch,78,76,82,78.05,1.41,00:00:06,0.00,0,0.00
7,Google Swag,63,57,80,41.25,5.10,00:04:14,0.00,0,0.00
8,google merch store,54,38,69,28.99,5.09,00:02:33,0.00,0,0.00
9,Google Clothing,39,36,49,40.82,3.98,00:02:43,0.00,0,0.00

Finally, we notice that the index of the DataFrame is now skipping from 0 to 2, so let's reset the index to avoid possible future errors:

In [69]:
ga_keywords.reset_index(inplace=True, drop=True)
ga_keywords

,Keyword,Users,New Users,Sessions,Bounce Rate,Pages/Session,Avg. Session Duration,E-commerce Conversion Rate,Transactions,Revenue
0,Google Merchandise Store,1051,753,1455,27.29,5.62,00:03:41,0.34,5,256.96
1,google merch,103,82,145,28.28,6.04,00:03:29,2.07,3,86.09
2,google backpack,95,68,121,40.50,4.20,00:02:27,0.00,0,0.00
3,Google Merchandise,93,54,147,28.57,5.37,00:03:23,0.68,1,79.98
4,Google Apparel,92,76,127,37.80,4.97,00:03:11,0.79,1,76.37
5,youtuber merch,78,76,82,78.05,1.41,00:00:06,0.00,0,0.00
6,Google Swag,63,57,80,41.25,5.10,00:04:14,0.00,0,0.00
7,google merch store,54,38,69,28.99,5.09,00:02:33,0.00,0,0.00
8,Google Clothing,39,36,49,40.82,3.98,00:02:43,0.00,0,0.00

---

### Exercise

Using the same `GA Paid Search Traffic.csv` file from the `data` folder as before, and the `pd.read_csv()` function that we've been using so far, load the "third block of data" from the file, that is, the Users' time series data.